---
version: 1

kind: experiment

framework: pytorch

tags: [examples]

#hptuning:
#  matrix:
#    normalization:
#      values: [True]
#    pretrained:
#      values: [True]
#    optimizer:
#      values: ["Adam"]
#    update_weights:
#      values: [False]


build:
  image: pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime
  build_steps:
    - pip install -r requirements.txt

environment:

  resources:
    cpu:
      requests: 3
      limits: 8
    memory:
      requests: 1024
      limits: 4098
    gpu:
      requests: 1
      limits: 1

declarations:
  batch_size: 64
  update_weights: True


run:
  cmd: python -u run_train_polyu.py  --batch_size={{ batch_size}} \
                                     --update_weights={{ update_weights }}\



